const Svelte = false
export default [
  { title: "Svelte", level: 5,icon:'svelte' },
  { title: "SvelteKit", level: 5,icon:'svelte' },
  { title: "JavaScript", level: 5,icon: 'javascript'},
  { title: "HTML", level: 5,icon:'html5' },
  { title: "Prisma", level: 5,icon:'prisma' },
  { title: "CSS", level: 4,icon:'css3' },
  { title: "Linux", level: 4,icon:'linux' },
  { title: "TypeScript", level: 4,icon:'typescript' },
  { title: "Socket.io", level:4,icon:'socketdotio'  },
  { title: "Jest", level: 4,icon:'jest' },
  { title: "NodeJS", level: 4,icon:'nodedotjs' },
  { title: "ExpressJS", level: 4,icon:'express' },
  { title: "Tailwind", level: 4,icon:'tailwindcss' },
  { title: "C#", level: 3,icon:'csharp' },
  { title: "Python", level: 3,icon:'python' },
  { title: "Lua", level: 3,icon:'lua' },
  { title: "ASP.NET", level:3,icon:'dotnet' },
  { title: "MySQL", level: 3,icon:'mysql' },
  { title: "SignalR", level: 3,icon:'dotnet' },
  { title: "Bash", level: 3,icon:'windowsterminal' },
]
