export default [
  { title: "Svelte", level: 5 },
  { title: "SvelteKit", level: 5 },
  { title: "JavaScript", level: 5 },
  { title: "HTML", level: 5 },
  { title: "Prisma", level: 5 },
  { title: "CSS", level: 4 },
  { title: "Linux", level: 4 },
  { title: "TypeScript", level: 4 },
  { title: "Socket.io", level: 4 },
  { title: "Jest", level: 4 },
  { title: "NodeJS", level: 4 },
  { title: "ExpressJS", level: 4 },
  { title: "Tailwind", level: 4 },
  { title: "Tailwind", level: 4 },
  { title: "C#", level: 3 },
  { title: "Python", level: 3 },
  { title: "Lua", level: 3 },
  { title: "ASP.NET", level: 3 },
  { title: "MySQL", level: 3 },
  { title: "SignalR", level: 3 },
  { title: "Bash", level: 3 },
]
